[project]
name = "axtk"
version = "0.1.0"
dependencies = [
    "ftfy",
    "lark",
    "tqdm",
    "regex",
    "torch",
    "anyascii",
    "pydantic",
    "pygtrie",
    "torchvision",
    "docstring_parser",
]
